[feature] 나의 심부름 페이지 메인 화면 퍼블리싱 완료
FRONTENDBOOTCAMP-11th/5MyGod pull request #19
Opened 2024-12-29 16:48 UTC by SHIN9018

## 🔍 PR 유형 (Type of PR)

어떤 변경사항인지 체크해주세요 (중복 체크 가능):

- [ ㅇ] ✨ 새로운 기능 추가
- [ ] 🐛 버그 수정
- [ㅇ ] 🎨 CSS 등 사용자 UI 디자인 변경
- [ ] 📝 코드에 영향을 주지 않는 변경사항 (오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] ♻️ 코드 리팩토링
- [ ] 💬 주석 추가 및 수정
- [ ] 📄 문서 수정
- [ ] 🧪 테스트 추가, 테스트 리팩토링
- [ ] 📦 빌드 또는 패키지 매니저 수정
- [ ] 🗂️ 파일 혹은 폴더명 수정
- [ ] 🗑️ 파일 혹은 폴더 삭제

---

## 📝 PR 설명 (Description)

- 변경 사항에 대한 간략한 설명을 작성해주세요.
- 퍼블리싱 완료 폰트 적용이 되는지 확인이 필요함 

---

## 🔗 관련 이슈 (Related Issues)

- 예시: `<라벨>/#<이슈번호>`  
  (이슈가 있다면 해당 번호를 참조하세요)
#4 
---

## 📸 스크린샷 (Screenshots)

- 변경 사항과 관련된 스크린샷이 있다면 추가해주세요.

---

## ✅ 체크리스트 (Checklist)

- [ ㅇ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ㅇ] 코드가 정상적으로 **컴파일**되고 모든 **테스트**를 통과했습니다.
- [ㅇ ] 필요한 경우 **주석**을 작성했습니다.
-fontFamily: {
        pretendard: ['Pretendard', 'sans-serif'],// Pretendard 폰트 추가
        laundry: ['LaundryGothic', 'sans-serif'], //LaundryGothic 폰트 추가
      },
- [ ㅇ] 관련 **문서**를 업데이트했습니다.

---

## 🛠 추가 정보 (Additional Information)

- 추가로 공유할 내용이 있으면 여기에 작성해주세요.

2024-12-30 00:30 UTC, bsh-ko approved these changes
👍

2024-12-30 00:31 UTC, ohgoodgood requested changes
수고하셨습니다~
그런데 테일윈드 설정들은 제가 이미 팀 전체에 적용해둔 상태라서, src/assets/styles/index.css 파일은 삭제해주시고, tailwind.config.js 파일은 develop 브랜치 pull 하셔서 최신화해주세요!

2024-12-30 01:35 UTC, underthemo-onlight approved these changes

2024-12-30 02:08 UTC, ohgoodgood requested changes
디렉토리 변경도 부탁드립니다!
html 문서 두개는 `5MyGod/src/pages/user` 아래로 옮겨주시고
이미지파일들은 제가 추가했으니 삭제해주시면 됩니다

2024-12-31 01:22 UTC, ohgoodgood approved these changes
👍🏻

2024-12-31 01:24 UTC, merged